"""empty message

Revision ID: 687cf9f66cf9
Revises: 9af40baf78ca
Create Date: 2020-03-01 16:53:01.555865

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '687cf9f66cf9'
down_revision = '9af40baf78ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('cust_nickname', table_name='tb_customer')
    op.drop_table('tb_customer')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tb_customer',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('cust_nickname', mysql.VARCHAR(length=32), nullable=False),
    sa.Column('cust_name', mysql.VARCHAR(length=32), nullable=True),
    sa.Column('cust_passwd', mysql.VARCHAR(length=32), nullable=True),
    sa.Column('cust_type', mysql.VARCHAR(length=10), nullable=True),
    sa.Column('cust_address', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('cust_active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('cust_remark', mysql.VARCHAR(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_index('cust_nickname', 'tb_customer', ['cust_nickname'], unique=True)
    # ### end Alembic commands ###
