"""empty message

Revision ID: 6ba9c5bf69e6
Revises: 687cf9f66cf9
Create Date: 2020-03-03 21:05:52.565000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ba9c5bf69e6'
down_revision = '687cf9f66cf9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tb_customer',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cust_nickname', sa.String(length=32), nullable=False),
    sa.Column('cust_name', sa.String(length=32), nullable=True),
    sa.Column('cust_passwd', sa.String(length=32), nullable=True),
    sa.Column('cust_type', sa.String(length=10), nullable=True),
    sa.Column('cust_address', sa.String(length=50), nullable=True),
    sa.Column('cust_active', sa.Boolean(), nullable=True),
    sa.Column('cust_remark', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cust_nickname')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tb_customer')
    # ### end Alembic commands ###
