"""empty message

Revision ID: 9af40baf78ca
Revises: 
Create Date: 2020-02-27 11:53:56.389384

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9af40baf78ca'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tb_category',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pid', sa.Integer(), nullable=True),
    sa.Column('category_name', sa.String(length=32), nullable=False),
    sa.Column('category_code', sa.String(length=32), nullable=True),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.Column('remark', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('category_name')
    )
    op.create_table('tb_commodity',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cate_id', sa.Integer(), nullable=False),
    sa.Column('product_name', sa.String(length=50), nullable=False),
    sa.Column('specification', sa.String(length=300), nullable=True),
    sa.Column('product_no', sa.String(length=32), nullable=True),
    sa.Column('product_detail', sa.String(length=500), nullable=True),
    sa.Column('product_type', sa.String(length=52), nullable=True),
    sa.Column('product_factory', sa.String(length=64), nullable=True),
    sa.Column('product_address', sa.String(length=52), nullable=True),
    sa.Column('brand', sa.String(length=52), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('remark', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tb_customer',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cust_nickname', sa.String(length=32), nullable=False),
    sa.Column('cust_name', sa.String(length=32), nullable=True),
    sa.Column('cust_passwd', sa.String(length=32), nullable=True),
    sa.Column('cust_type', sa.String(length=10), nullable=True),
    sa.Column('cust_address', sa.String(length=50), nullable=True),
    sa.Column('cust_active', sa.Boolean(), nullable=True),
    sa.Column('cust_remark', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cust_nickname')
    )
    op.create_table('tb_user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=32), nullable=False),
    sa.Column('nickname', sa.String(length=32), nullable=False),
    sa.Column('password', sa.String(length=32), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('remark', sa.String(length=300), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nickname'),
    sa.UniqueConstraint('username')
    )
    op.create_table('tb_photo',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('photo_name', sa.String(length=50), nullable=True),
    sa.Column('photo_url', sa.String(length=50), nullable=True),
    sa.Column('remarkd', sa.String(length=200), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['tb_commodity.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tb_photo')
    op.drop_table('tb_user')
    op.drop_table('tb_customer')
    op.drop_table('tb_commodity')
    op.drop_table('tb_category')
    # ### end Alembic commands ###
